### ISSUE TITLE
Conda is being really annoying

### ISSUE THREAD

**Issue by sydhenry** [matty-jones/blaskbot#1]
I started with this error

```
(chroot)sydney@localhost:~/repos/blaskbot$ conda env create -f requirements.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
NoPackagesFoundError: Package missing in current linux-64 channels: 
  - tinydb 3.5.0*
```

By moving it under `pip` it then seems to find it. That then causes issues with `six` not being seen. I have tried a ton of different permutations and I get stuff like this:

```
(chroot)sydney@localhost:~/repos/blaskbot$ conda env create -f requirements.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........
Linking packages ...
[      COMPLETE      ]|######################| 100%
Collecting six==1.11.0
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /home/sydney/.local/lib/python3.6/site-packages
Collecting tinydb==3.5.0
  Using cached tinydb-3.5.0.tar.gz
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/home/sydney/anaconda3/envs/blaskbot/lib/python3.6/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/home/sydney/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ModuleNotFoundError: No module named 'six'

CondaValueError: Value error: pip returned an error.
```

As you can see, `six` is there for setuptools and it then doesn't see it. 

There will be a pull request for my final `requirements.yml` that works on my ubuntux64

**Comment by matty-jones** [comment]
Yeah, when I initialise from scratch I get the tinydb package missing error too, but removing tinydb from the requirements and doing a `pip install tinydb==3.5.0` fixes it (as I noted in the readme).

Not sure why conda can't install it from the yml, perhaps it just makes more sense to migrate over to redis or postgres or something to avoid this completely. The databases are small at the moment so it just felt like overkill.

**Comment by sydhenry** [comment]
Think I missed that in the readme. What I am use to is using is `virtualenv`, or more recently conda to make the environment then do `pip install -r requirements.txt`. The conda yml seems to be good for more extensive deps that come from all over, be it apt-get, npm, or node. With the commit that you merged it seems like conda is fine to use. I mainly didn't want to have to use conda and pip both to install Python packages.

As for a more powerful database, that can be troublesome. I have some SQL experience, but I mainly interact through django which solves crafting the scheme and SQL commands. I'm not sure when tinydb gets ineffective, but if you are planing on doing achievements you might want to make the switch sooner. I assume it would make heavy use of the db and that would require a ton of rewrite from tinydb. Also don't want to get to the point of querying in the seconds, but not changing it because of the large rewrite that would be needed.

On September 22, 2017 10:06:11 AM MST, Matty Jones <notifications@github.com> wrote:
>Yeah, when I initialise from scratch I get the tinydb package missing
>error too, but removing tinydb from the requirements and doing a `pip
>install tinydb==3.5.0` fixes it (as I noted in the readme).
>
>Not sure why conda can't install it from the yml, perhaps it just makes
>more sense to migrate over to redis or postgres or something to avoid
>this completely. The databases are small at the moment so it just felt
>like overkill.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matty-jones/blaskbot/issues/1#issuecomment-331504605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
